 Problem- 1: Array Creation:


In [ ]:
# Step 0: Import numpy
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Task 1 - Empty Array 2x2:\n", empty_array)

# Task 2: Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nTask 2 - All Ones Array 4x2:\n", ones_array)

# Task 3: Return a new array of given shape and type, filled with a fill value
filled_array = np.full((3, 3), 7)
print("\nTask 3 - Filled Array 3x3 with 7:\n", filled_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1,2,3],[4,5,6]])
zeros_like_array = np.zeros_like(given_array)
print("\nTask 4 - Zeros Like Given Array:\n", zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nTask 5 - Ones Like Given Array:\n", ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
list_to_array = np.array(new_list)
print("\nTask 6 - List Converted to Numpy Array:\n", list_to_array)


Task 1 - Empty Array 2x2:
 [[4.73517544e-315 0.00000000e+000]
 [6.52469749e-310 6.52469750e-310]]

Task 2 - All Ones Array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Task 3 - Filled Array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Task 4 - Zeros Like Given Array:
 [[0 0 0]
 [0 0 0]]

Task 5 - Ones Like Given Array:
 [[1 1 1]
 [1 1 1]]

Task 6 - List Converted to Numpy Array:
 [1 2 3 4]


Problem-2: Array Manipulation

In [ ]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Task 1 - Array 10 to 49:\n", array_10_49)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3,3))
print("\nTask 2 - 3x3 Matrix 0 to 8:\n", matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nTask 3 - 3x3 Identity Matrix:\n", identity_matrix)

# Task 4: Create a random array of size 30 and find its mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nTask 4 - Random Array 30 Elements:\n", random_array_30)
print("Mean of Random Array:", mean_value)

# Task 5: Create a 10x10 array with random values and find min and max
random_array_10x10 = np.random.random((10,10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\nTask 5 - 10x10 Random Array:\n", random_array_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# Task 6: Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1   # Indexing starts at 0
print("\nTask 6 - Zero Array with 5th Element as 1:\n", zero_array)

# Task 7: Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print("\nTask 7 - Reversed Array:\n", reversed_arr)

# Task 8: Create a 2D array with 1 on the border and 0 inside
n = 5  # Example size 5x5
border_array = np.ones((n,n))
border_array[1:-1, 1:-1] = 0
print("\nTask 8 - 2D Array with Border 1s and Inside 0s:\n", border_array)

# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nTask 9 - 8x8 Checkerboard Pattern:\n", checkerboard)


Task 1 - Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

Task 2 - 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3 - 3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4 - Random Array 30 Elements:
 [0.05678964 0.98884211 0.60751162 0.0114411  0.0692075  0.29733036
 0.29051351 0.66385333 0.64685583 0.88722032 0.54841144 0.58880159
 0.06372754 0.38898441 0.84118165 0.21004577 0.22283666 0.28444803
 0.4293679  0.44390005 0.78615621 0.42774341 0.20214099 0.52273759
 0.91769636 0.02172941 0.11750005 0.17495137 0.84097034 0.2734092 ]
Mean of Random Array: 0.4275435107574556

Task 5 - 10x10 Random Array:
 [[0.87281711 0.01106571 0.73861856 0.66440369 0.71930625 0.40220961
  0.73115618 0.61880731 0.29945923 0.39650077]
 [0.40017061 0.0023922  0.08981051 0.90617071 0.5834412  0.55553586
  0.07327029 0.14900702 0.82843045 0.91838388]
 [0.57863688 0.82979687 0.9427063  0.5818533  0.1

Problem-3: Array Operations

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
add_xy = x + y
print("Task 1 - x + y:\n", add_xy)

# Task 2: Subtract the two arrays
sub_xy = x - y
print("\nTask 2 - x - y:\n", sub_xy)

# Task 3: Multiply the array with an integer (let's choose 3)
mul_x = x * 3
print("\nTask 3 - x * 3:\n", mul_x)

# Task 4: Square of each element
square_x = x**2
print("\nTask 4 - Square of x:\n", square_x)

# Task 5: Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nTask 5 - Dot Product:")
print("v . w =", dot_vw)
print("x . v =", dot_xv)
print("x . y =\n", dot_xy)

# Task 6: Concatenate x and y along row (axis=0) and v and w along column (axis=1)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.vstack((v, w)).T  # transpose to make column
print("\nTask 6 - Concatenation:")
print("x and y along row:\n", concat_xy_row)
print("v and w along column:\n", concat_vw_col)

# Task 7: Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nTask 7 - Concatenate x and v Error:\n", e)
    print("Explanation: Cannot concatenate x (2x2) with v (1x2) along axis=0 because the number of columns must match. For axis=1, number of rows must match. Shapes must align.")



Task 1 - x + y:
 [[ 6  8]
 [10 13]]

Task 2 - x - y:
 [[-4 -4]
 [-4 -3]]

Task 3 - x * 3:
 [[ 3  6]
 [ 9 15]]

Task 4 - Square of x:
 [[ 1  4]
 [ 9 25]]

Task 5 - Dot Product:
v . w = 219
x . v = [29 77]
x . y =
 [[19 22]
 [50 58]]

Task 6 - Concatenation:
x and y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along column:
 [[ 9 11]
 [10 12]]

Task 7 - Concatenate x and v Error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate x (2x2) with v (1x2) along axis=0 because the number of columns must match. For axis=1, number of rows must match. Shapes must align.


Problem 4: Matrix Operations

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A * A_inv = I
A_inv = np.linalg.inv(A)  # Inverse of A
identity_check = np.dot(A, A_inv)
print("Task 1 - A * A_inv:\n", identity_check)

# Task 2: Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nTask 2 - AB:\n", AB)
print("BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T * A^T
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)
print("\nTask 3 - (AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_TA_T)
print("Check equality:", np.array_equal(AB_T, B_TA_T))

# Task 4: Solve system of linear equations using matrix inverse
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent in matrix form AX = B
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Solve using inverse
A_matrix_inv = np.linalg.inv(A_matrix)
X_solution = np.dot(A_matrix_inv, B_matrix)
print("\nTask 4 - Solution using inverse method:\n", X_solution)

# Optional: Solve using np.linalg.solve (more efficient)
X_solution_solve = np.linalg.solve(A_matrix, B_matrix)
print("Solution using np.linalg.solve:\n", X_solution_solve)


Task 1 - A * A_inv:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Task 2 - AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB == BA? False

Task 3 - (AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Check equality: True

Task 4 - Solution using inverse method:
 [ 2.  1. -2.]
Solution using np.linalg.solve:
 [ 2.  1. -2.]
